[package]
name = "openssl_heartbleed"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 2024.04.02
libafl = { version = "0.11.2" }
libafl_bolts = { version = "0.11.2" } 